<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header">
    <h1>User overview</h1>
</div>

<div class="row">
    <div class="col-sm-12">
        <?php echo $this->tag->form([
            "users/search",
            "autocomplete" => "off",
            "class=" => "form-inline"
        ]);
        ?>

        <div class="input-group">
            <label for="search" class="sr-only">Search</label>
            <?php echo $this->tag->textField(["search", "class" => "form-control", "id" => "fieldUserSearch", "placeholder" => "Search users"]); ?>
            <span class="input-group-btn">
                <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]); ?>
            </span>
        </div>

        <?php echo $this->tag->endForm(); ?>
    </div>
</div>

<?php echo $this->getContent() ?>

<div class="row">
    <table class="table table-bordered" id="userTable">
        <thead>
        <tr>
            <th>Username</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->username ?></td>
                <td><?php echo $user->first_name ?></td>
                <td><?php echo $user->last_name ?></td>
                <td><?php echo $user->email ?></td>

                <td class="admin">
                    <?php

                    echo $this->tag->form("users/admin");
                    echo $this->tag->hiddenField(["id", "value" => $user->id]);
                    echo $this->tag->hiddenField(["page", "value" => $page->current]);
                    if ($user->is_admin == 0) {
                        echo $this->tag->submitButton(["No admin", "class" => "btn btn-danger"]);
                    } else {
                        echo $this->tag->submitButton(["Admin", "class" => "btn btn-success"]);
                    }
                    echo $this->tag->endForm();

                    ?>
                </td>
                <td class="delete"><?php echo $this->tag->linkTo(["users/delete/" . $user->id, "Delete", "role" => "button", "class" => "btn btn-primary"]) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("users", "First") ?></li>
                <li><?php echo $this->tag->linkTo("users?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("users?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("users?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
