<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["admin", "Return to admin page"]); ?></li>
            <li class="next">
                <?php echo $this->tag->form(
                    [
                        "users/search",
                        "autocomplete" => "off",
                        "class" => "form-inline text-right"
                    ]
                );
                ?>

                <div class="form-group">
                    <label for="parameters" class="sr-only"></label>
                    <?php echo $this->tag->searchField(["username", "size" => "15", "class" => "form-control", "id" => "fieldUsername", "placeholder" => "Search users"]) ?>
                </div>

                <div class="form-group">
                    <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
                </div>

                <?php echo $this->tag->endForm(); ?>
            </li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Users</h1>
</div>

<?php echo $this->getContent() ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Username</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th>Admin?</th>

            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->username ?></td>
                <td><?php echo $user->first_name ?></td>
                <td><?php echo $user->last_name ?></td>
                <td><?php echo $user->email ?></td>
                <td><?php echo ($user->is_admin == 1 ? "Yes" : "No") ?></td>

                <td><?php echo $this->tag->linkTo(["users/edit/" . $user->id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["users/delete/" . $user->id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("users", "First") ?></li>
                <li><?php echo $this->tag->linkTo("users?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("users?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("users?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
