<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Lineups
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["lineups/new", "Create lineups"]) ?>
    </p>
</div>

<div class="row">
    <div class="col-sm-6">
        <?php echo $this->tag->linkTo(["admin", "Return to admin page", "role" => "button", "class" => "btn btn-default"]); ?>
    </div>
    <div class="col-sm-6">
        <?php echo $this->tag->form([
            "lineups/search",
            "autocomplete" => "off",
            "class=" => "form-inline text-right"
        ]);
        ?>

        <div class="input-group">
            <label for="parameters" class="sr-only">Parameters</label>
            <?php echo $this->tag->textField(["search", "class" => "form-control", "id" => "fieldLineupSearch", "placeholder" => "Search lineups"]); ?>
            <span class="input-group-btn">
                <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]); ?>
            </span>
        </div>

        <?php echo $this->tag->endForm(); ?>
    </div>
</div>

<?php echo $this->getContent() ?>

<div class="row">
    <table class="table table-bordered" id="lineupTable">
        <thead>
        <tr>
            <th>Created by</th>
            <th>GK</th>
            <th>RB</th>
            <th>RCB</th>
            <th>LCB</th>
            <th>LB</th>
            <th>RCM</th>
            <th>CM</th>
            <th>LCM</th>
            <th>RW</th>
            <th>ST</th>
            <th>LW</th>
            <th>Created on</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $lineup): ?>
            <?php
            $positions = Positions::find("lineup_id = '" . $lineup->id . "'");
            $players = [];

            foreach ($positions as $position):
                $players[] = Players::findFirstByid($position->player_id);
            endforeach
            ?>

            <tr>
                <td>
                    <?php
                    $user = Users::findFirstByid($lineup->user_id);
                    echo $user->username
                    ?>
                </td>
                <?php foreach ($players as $player): ?>
                    <td><?php echo $player->first_name[0] . ". " . $player->last_name ?></td>
                <?php endforeach ?>
                <td><?php echo $lineup->date_added ?></td>
                <td class="rating <?php
                switch ($lineup->average_rating):
                case $lineup->average_rating < 2.0:
                    echo "onetwo";
                    break;
                case $lineup->average_rating < 3.0:
                    echo "twothree";
                    break;
                case $lineup->average_rating < 4.0:
                    echo "threefour";
                    break;
                case $lineup->average_rating < 5.0:
                    echo "fourfive";
                    break;
                case $lineup->average_rating < 6.0:
                    echo "fivesix";
                    break;
                case $lineup->average_rating < 7.0:
                    echo "sixseven";
                    break;
                case $lineup->average_rating < 8.0:
                    echo "seveneight";
                    break;
                case $lineup->average_rating < 9.0:
                    echo "eightnine";
                    break;
                default:
                    echo "nineten";
                    break;
                endswitch
                ?>">
                    <?php echo $lineup->average_rating ?>
                </td>
            </tr>
            <tr>
                <td colspan="3" class="rate">Rate this lineup:</td>
                <td colspan="11" class="rateForm">
                    <?php

                    echo $this->tag->form([
                        "lineups/rate",
                        "class" => "form-inline"
                    ]);

                    echo $this->tag->hiddenField(["id", "value" => $lineup->id]);
                    echo $this->tag->hiddenField(["page", "value" => $page->current]);

                    ?>
                    <div class="form-group select">
                        <label for="userField" class="sr-only">User:</label>
                        <?php echo $this->tag->select([
                            "userField",
                            Users::find(),
                            "using" => ["id", "username"]
                            ]);
                        ?>
                    </div>
                    <small>1</small>
                    <div class="form-group">
                        <label for="ratingField" class="sr-only">Rating:</label>
                        <?php echo $this->tag->rangeField([
                            "ratingField",
                            "min"   => 1,
                            "max"   => 10,
                            "value" => 6,
                            "list"  => "ratingValues"
                            ]);
                        ?>
                        <datalist id="ratingValues">
                            <?php for ($i = 1; $i < 11; $i++): ?>
                                <option value="<?php echo $i ?>">
                            <?php endfor ?>
                        </datalist>
                    </div>
                    <small>10</small>
                    <div class="form-group submit">
                        <?php echo $this->tag->submitButton([
                            "Rate",
                            "class" => "btn btn-primary"
                            ]);
                        ?>
                    </div>
                    <?php echo $this->tag->endForm() ?>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("lineups", "First") ?></li>
                <li><?php echo $this->tag->linkTo("lineups?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("lineups?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("lineups?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
