<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["lineups/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["lineups/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <?php
    $user = Users::findFirstByid($page->items[0]->user_id)
    ?>
    <h1>Showing lineups created by: <?php echo $user->username ?></h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered" id="lineupTable">
        <thead>
        <tr>
            <th>Created by</th>
            <th>GK</th>
            <th>RB</th>
            <th>RCB</th>
            <th>LCB</th>
            <th>LB</th>
            <th>RCM</th>
            <th>CM</th>
            <th>LCM</th>
            <th>RW</th>
            <th>ST</th>
            <th>LW</th>
            <th>Created on</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $lineup): ?>
            <?php
            $positions = Positions::find("lineup_id = '" . $lineup->id . "'");
            $players = [];

            foreach ($positions as $position):
                $players[] = Players::findFirstByid($position->player_id);
            endforeach
            ?>

            <tr>
                <td>
                    <?php
                    $user = Users::findFirstByid($lineup->user_id);
                    echo $user->username
                    ?>
                </td>
                <?php foreach ($players as $player): ?>
                    <td><?php echo $player->first_name[0] . ". " . $player->last_name ?></td>
                <?php endforeach ?>
                <td><?php echo $lineup->date_added ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("lineups/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("lineups/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("lineups/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("lineups/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
