<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["admin", "Return to admin page"]); ?></li>
            <li class="next">
                <?php echo $this->tag->form(
                    [
                        "players/search",
                        "autocomplete" => "off",
                        "class" => "form-inline text-right"
                    ]
                );
                ?>

                <div class="form-group">
                    <label for="parameters" class="sr-only"></label>
                    <?php echo $this->tag->searchField(["last_name", "size" => "15", "class" => "form-control", "id" => "fieldLastName", "placeholder" => "Search players"]) ?>
                </div>

                <div class="form-group">
                    <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
                </div>

                <?php echo $this->tag->endForm(); ?>
            </li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Unapproved players</h1>
</div>

<?php echo $this->getContent() ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Nationality</th>
            <th>Club</th>
            <th>Position</th>

            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $player): ?>
            <tr>
                <td><?php echo $player->first_name ?></td>
                <td><?php echo $player->last_name ?></td>
                <td><?php echo $player->nationality ?></td>
                <td><?php echo $player->club ?></td>
                <td><?php echo $player->position ?></td>

                <td><?php echo $this->tag->linkTo(["players/approve/" . $player->id, "Approve"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("players", "First") ?></li>
                <li><?php echo $this->tag->linkTo("players?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("players?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("players?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>

<?php
//    echo $this->tag->form(
//        [
//            "players/search",
//            "autocomplete" => "off",
//            "class" => "form-horizontal"
//        ]
//    );
//?>
<!---->
<!--<div class="form-group">-->
<!--    <label for="fieldFirstName" class="col-sm-2 control-label">First name</label>-->
<!--    <div class="col-sm-10">-->
<!--        --><?php //echo $this->tag->textField(["first_name", "size" => 30, "class" => "form-control", "id" => "fieldFirstName"]) ?>
<!--    </div>-->
<!--</div>-->
<!---->
<!--<div class="form-group">-->
<!--    <label for="fieldLastName" class="col-sm-2 control-label">Last name</label>-->
<!--    <div class="col-sm-10">-->
<!--        --><?php //echo $this->tag->textField(["last_name", "size" => 30, "class" => "form-control", "id" => "fieldLastName"]) ?>
<!--    </div>-->
<!--</div>-->
<!---->
<!--<div class="form-group">-->
<!--    <label for="fieldNationality" class="col-sm-2 control-label">Nationality</label>-->
<!--    <div class="col-sm-10">-->
<!--        --><?php //echo $this->tag->textField(["nationality", "size" => 30, "class" => "form-control", "id" => "fieldNationality"]) ?>
<!--    </div>-->
<!--</div>-->
<!---->
<!--<div class="form-group">-->
<!--    <label for="fieldClub" class="col-sm-2 control-label">Club</label>-->
<!--    <div class="col-sm-10">-->
<!--        --><?php //echo $this->tag->textField(["club", "size" => 30, "class" => "form-control", "id" => "fieldClub"]) ?>
<!--    </div>-->
<!--</div>-->
<!---->
<!--<div class="form-group">-->
<!--    <div class="col-sm-offset-2 col-sm-10">-->
<!--        --><?php //echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
<!--    </div>-->
<!--</div>-->
<!---->
<?php //echo $this->tag->endForm(); ?>
