<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search players
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["players/new", "Create players"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "players/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldFirstName" class="col-sm-2 control-label">First name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["first_name", "size" => 30, "class" => "form-control", "id" => "fieldFirstName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastName" class="col-sm-2 control-label">Last name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["last_name", "size" => 30, "class" => "form-control", "id" => "fieldLastName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNationality" class="col-sm-2 control-label">Nationality</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nationality", "size" => 30, "class" => "form-control", "id" => "fieldNationality"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldClub" class="col-sm-2 control-label">Club</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["club", "size" => 30, "class" => "form-control", "id" => "fieldClub"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
