<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["players/index", "Go back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["players/new", "Add player"]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered" id="playerTable">
        <thead>
        <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Nationality</th>
            <th>Club</th>
            <th>Position</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $player): ?>
            <tr>
                <td><?php echo $player->first_name ?></td>
                <td><?php echo $player->last_name ?></td>
                <td><?php echo $player->nationality ?></td>
                <td><?php echo $player->club ?></td>
                <td><?php echo $player->position ?></td>

                <?php if ($this->session->get("admin") == 1): ?>
                    <td class="approve">
                        <?php

                        echo $this->tag->form("players/approve");
                        echo $this->tag->hiddenField(["id", "value" => $player->id]);
                        echo $this->tag->hiddenField(["page", "value" => $page->current]);
                        if ($player->is_approved == 0) {
                            echo $this->tag->submitButton(["Approve", "class" => "btn btn-success"]);
                        } else {
                            echo $this->tag->submitButton(["Unapprove", "class" => "btn btn-danger"]);
                        }
                        echo $this->tag->endForm();

                        ?>
                    </td>
                    <td class="edit"><?php echo $this->tag->linkTo(["players/edit/" . $player->id, "Edit", "role" => "button", "class" => "btn btn-primary"]) ?></td>
                    <td class="delete"><?php echo $this->tag->linkTo(["players/delete/" . $player->id, "Delete", "role" => "button", "class" => "btn btn-primary"]) ?></td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("players/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("players/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("players/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("players/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
